name: Deploy Static Website to Nginx

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

    - name: Deploy HTML files via rsync
      run: |
        rsync -avz --delete ./static-site/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/var/www/mywebsite/

    - name: Reload Nginx
      run: |
        ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "sudo systemctl reload nginx"
